CREATE TABLE USERS
(
    ID BIGINT PRIMARY KEY NOT NULL IDENTITY,
    NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL
);
CREATE UNIQUE INDEX table_name_email_uindex ON USERS (EMAIL);
CREATE UNIQUE INDEX table_name_name_uindex ON USERS (PASSWORD);
